server:
  port: 9000
spring:
  application:
    name: ribbon-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
      
#ribbon:
#  eureka:
#   enabled: false      
      
#baidu: 
#  ribbon:
#    listOfServers: www.baidu.com 